### ISSUE TITLE
How to map an Asset field in schema to c#

### ISSUE THREAD

**Issue by rustymcg9000** [Squidex/squidex-samples#11]
I have a schema (my-bio), that just contains 2 string fields and 1 asset field (for an image).
I am now trying to retrieve the content using the SquidexClient<TEntity, TData> but what c# data type should I be using for the asset field so I can get a url to the image ?

**Comment by SebastianStehle** [comment]
The asset field contains Ids only, so it would map to 

* `string[]`
* `List<string>`
* `Guid[]`
* `List<Guid>`
* ... most other collections

. But there are some helper methods to convert it to an url.

Btw: Please use our support forum the next time: https://support.squidex.io
