### ISSUE TITLE
Latest Client Library Issue: Cannot access a disposed object

### ISSUE THREAD

**Issue by Jaben** [Squidex/squidex-samples#18]
If I make two calls with the same client instance, I now get:

![image](https://user-images.githubusercontent.com/448726/51565519-37995480-1e60-11e9-89d2-de66269a55da.png)

This is a new issue with the latest version of the client.

Thanks!

**Comment by Jaben** [comment]
It looks like HttpClient is disposing of the HttpClientHandler on each request -- I modified my client to create a new AuthenticatingHttpClientHandler() object per client instance and it works now.

**Comment by SebastianStehle** [comment]
Mhm, thank you, I will investigate it more. A small sample to reproduce it would be great.
