### ISSUE TITLE
Cannot create a new entry

### ISSUE THREAD

**Issue by Jaben** [Squidex/squidex-samples#19]
GetAsync() works perfectly -- but I cannot create an new entry. The schema:

```javascript
{
    "fields": [
        {
            "name": "Model",
            "properties": {
                "editor": "Input",
                "fieldType": "String"
            },
            "partitioning": "invariant"
        }
    ],
    "properties": {}
}
```

The code:

```csharp
{
	var client = clientManager.GetClient<FanModelSquidex, FanModelData>("fanmodel");
	var data = new FanModelData() { Model = "DU" };
	var result = await client.CreateAsync(data, true);
}

public class FanModelSquidex : SquidexEntityBase<FanModelData>
{
}

public class FanModelData
{
	[JsonConverter(typeof(InvariantConverter))]
	public string Model { get; set; }
}
```

Results in:

![image](https://user-images.githubusercontent.com/448726/51565994-75e34380-1e61-11e9-9022-94096cfb1783.png)

Thanks!

**Comment by SebastianStehle** [comment]
By default the client library converts all property names from PascalCase to camelCase, but field names in Squidex are case sensitive. Therefore it fails with this exception. The KeepCasing Attribute disables the conversion.

**Comment by Jaben** [comment]
The default is it doesn't work? Not exactly a great user experience....

**Comment by SebastianStehle** [comment]
No, I made the assumption that most people would name their schema fields with camelCase and there was a validation rule to enforce that before I got complains to change it. Now it is too late to make the schema system case insensitive.

How would you solve it?

**Comment by Jaben** [comment]
I see. Yeah, it's a complex situation.

One solution would be a simplistic code generator in Squidex that gens a working .cs model.

**Comment by Jaben** [comment]
Another option would be a simplistic schema pull of the endpoint to check the data structure.

**Comment by Jaben** [comment]
We can close this for now -- I at least have a way forward :)
