### ISSUE TITLE
Missing type/namespace?

### ISSUE THREAD

**Issue by blakecodes** [Squidex/squidex-samples#25]
Just pulled in the most recent code for the client library and I'm getting these two errors:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'TestSDKAutoGeneratedCodeAttribute' does not exist in the namespace 'Microsoft.VisualStudio.TestPlatform' (are you missing an assembly reference?)	Squidex.ClientLibrary.Tests	C:\Users\Blake\Desktop\SeqTek\evetv4\squidex-samples\csharp\Squidex.ClientLibrary\Squidex.ClientLibrary.Tests\obj\Debug\netcoreapp2.0\Squidex.ClientLibrary.Tests.Program.cs	3	Active
`

--

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'TestSDKAutoGeneratedCode' does not exist in the namespace 'Microsoft.VisualStudio.TestPlatform' (are you missing an assembly reference?)	Squidex.ClientLibrary.Tests	C:\Users\Blake\Desktop\SeqTek\evetv4\squidex-samples\csharp\Squidex.ClientLibrary\Squidex.ClientLibrary.Tests\obj\Debug\netcoreapp2.0\Squidex.ClientLibrary.Tests.Program.cs	3	Active
`

**Comment by SebastianStehle** [comment]
It was building for me, but if it is solved now: Great :)

**Comment by SebastianStehle** [comment]
Lol, you are fast :D

**Comment by blakecodes** [comment]
@SebastianStehle haha :)
