### ISSUE TITLE
CreateAsync is posting to an incorrect path

### ISSUE THREAD

**Issue by klavs** [Squidex/squidex-samples#4]
[Client library](https://github.com/Squidex/squidex-samples/blob/master/csharp/Squidex.ClientLibrary/Squidex.ClientLibrary/SquidexClient.cs#L93)

[Api controller](https://github.com/Squidex/squidex/blob/master/src/Squidex/Areas/Api/Controllers/Content/ContentsController.cs#L231)

**Comment by SebastianStehle** [comment]
Thank you. I fixed the bug and also created some integration tests to ensure that it is stable now.
